name: Update Wiki

on: [ push ]
jobs:
  update-wiki:
    runs-on: ubuntu-latest
    name: Update wiki
    steps:
      - name: test script
        run: ./.github/scripts/update.sh
        shell: bash
        env:
          WIKI_DIR: ${{ inputs.path }}
          GH_TOKEN: ${{ inputs.token }}