name: Update Wiki

on: [ push ]
jobs:
  update-wiki:
    runs-on: ubuntu-latest
    name: Update wiki
    steps:
      - uses: actions/checkout@v2
        run: |
          echo
      - uses: ./.github/actions/update
        with:
          path: 'wiki'
          token: ${{ secrets.GITHUB_TOKEN }}