name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [ push ]
jobs:
  update-wiki:
    runs-on: ubuntu-latest
    name: Update wiki
    steps:
      - uses: OrlovM/Wiki-Action@v1
        with:
          path: './Bomberman.wiki'
          token: ${{ secrets.GITHUB_TOKEN }}